In [2]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [72]:
movies_data = pd.read_csv(r"C:\Users\dakid\Downloads\Compressed\End-to-End-Movie-Recommendation-System-main\Artifacts\TMDB_all_movies.csv")

In [73]:
movies_data.head()

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,budget,imdb_id,...,spoken_languages,cast,director,director_of_photography,writers,producers,music_composer,imdb_rating,imdb_votes,poster_path
0,2,Ariel,7.1,367.0,Released,1988-10-21,0.0,73.0,0.0,tt0094675,...,suomi,"Tarja Keinänen, Marja Packalén, Kari Helaseppä...",Aki Kaurismäki,Timo Salminen,Aki Kaurismäki,Aki Kaurismäki,NaN,7.4,9629.0,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg
1,3,Shadows in Paradise,7.3,430.0,Released,1986-10-17,0.0,74.0,0.0,tt0092149,...,"svenska, suomi, English","Haije Alanoja, Mari Rantasila, Matti Pellonpää...",Aki Kaurismäki,Timo Salminen,Aki Kaurismäki,Mika Kaurismäki,NaN,7.4,8497.0,/nj01hspawPof0mJmlgfjuLyJuRN.jpg
2,5,Four Rooms,5.9,2799.0,Released,1995-12-09,4257354.0,98.0,4000000.0,tt0113101,...,English,"Antonio Banderas, Ione Skye, Sammi Davis, Paul...","Allison Anders, Quentin Tarantino, Alexandre R...","Andrzej Sekula, Rodrigo García, Guillermo Nava...","Allison Anders, Quentin Tarantino, Alexandre R...","Lawrence Bender, Quentin Tarantino, Alexandre ...",Combustible Edison,6.7,116434.0,/75aHn1NOYXh4M7L5shoeQ6NGykP.jpg
3,6,Judgment Night,6.5,360.0,Released,1993-10-15,12136938.0,109.0,21000000.0,tt0107286,...,English,"Doug Wert, Angela Alvarado, Everlast, Sean O'G...",Stephen Hopkins,Peter Levy,"Lewis Colick, Jere Cunningham","Marilyn Vance, Gene Levy, Lloyd Segan",Alan Silvestri,6.6,20857.0,/3rvvpS9YPM5HB2f4HYiNiJVtdam.jpg
4,8,Life in Loops (A Megacities RMX),7.2,30.0,Released,2006-01-01,0.0,80.0,42000.0,tt0825671,...,"English, हिन्दी, 日本語, Pусский, Español",NaN,Timo Novotny,Wolfgang Thaler,"Timo Novotny, Michael Glawogger","Timo Novotny, Ulrich Gehmacher",NaN,8.1,285.0,/7ln81BRnPR2wqxuITZxEciCe1lc.jpg


In [74]:
movies_data.shape

(1162949, 28)

In [75]:
movies_data = movies_data.sample(50000, random_state=42)

In [76]:
movies_data = movies_data.reset_index(drop=True)
movies_data['title'] = movies_data['title'].fillna('')
list_of_all_titles = movies_data['title'].tolist()

In [77]:
print(movies_data.columns)

Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'budget', 'imdb_id', 'original_language',
       'original_title', 'overview', 'popularity', 'tagline', 'genres',
       'production_companies', 'production_countries', 'spoken_languages',
       'cast', 'director', 'director_of_photography', 'writers', 'producers',
       'music_composer', 'imdb_rating', 'imdb_votes', 'poster_path'],
      dtype='str')


In [79]:
selected_features = ['genres','overview','tagline','cast','director','writers']
print(selected_features)

['genres', 'overview', 'tagline', 'cast', 'director', 'writers']


In [80]:
for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [81]:
combined_features = movies_data['genres'] + ' ' + movies_data['overview'] + ' ' + movies_data['tagline'] + ' ' + movies_data['cast'] + ' ' + movies_data['director'] + ' ' + movies_data['writers']

In [82]:
print(combined_features)

0        Crime, Thriller, Action After Zerina's father ...
1        Drama Living without parents, Zhanna and Roman...
2        Drama A saga through the difficulties of sayin...
3         In a small desert village, the inhabitants ar...
4        Documentary The Kent workers busily stripping ...
                               ...                        
49995    Documentary Grandma Haya decides to stop eatin...
49996    Documentary, Drama A youngster writes a letter...
49997    Drama During World War II, a group of young an...
49998     A Danish crime film about a master criminal w...
49999    Thriller Sly and dry intelligence agent Harry ...
Length: 50000, dtype: str


In [83]:
vectorizer = TfidfVectorizer()

In [84]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [85]:
print(feature_vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2297975 stored elements and shape (50000, 207875)>
  Coords	Values
  (0, 39433)	0.057591275596104274
  (0, 182208)	0.05426763506129434
  (0, 2374)	0.05457202724116871
  (0, 3399)	0.09700397364867451
  (0, 203431)	0.15345381828527613
  (0, 57784)	0.0592305563875574
  (0, 66110)	0.06679870897836099
  (0, 11476)	0.1266166918551462
  (0, 60894)	0.0345529228415952
  (0, 96091)	0.09664589142158557
  (0, 184119)	0.07377100973271501
  (0, 123254)	0.07320630313206264
  (0, 181480)	0.038898150235619655
  (0, 120693)	0.10328584947311861
  (0, 172678)	0.07637116957834963
  (0, 68056)	0.07502158608934524
  (0, 76161)	0.11794419670867708
  (0, 10958)	0.03838323845643193
  (0, 196589)	0.06798118240876086
  (0, 132715)	0.05566488988049543
  (0, 138908)	0.07916166384313424
  (0, 181422)	0.036247420342717294
  (0, 29036)	0.05517953958653116
  (0, 159894)	0.07381377427794504
  (0, 130226)	0.0632926877341648
  :	:
  (49999, 27263)	0.12083762888

In [86]:
similarity = cosine_similarity(feature_vectors)

In [87]:
print(similarity)

[[1.         0.01067987 0.00714445 ... 0.00357083 0.00531494 0.00893686]
 [0.01067987 1.         0.01463332 ... 0.02185131 0.00438048 0.03356685]
 [0.00714445 0.01463332 1.         ... 0.01642347 0.         0.01193482]
 ...
 [0.00357083 0.02185131 0.01642347 ... 1.         0.         0.01197539]
 [0.00531494 0.00438048 0.         ... 0.         1.         0.00159366]
 [0.00893686 0.03356685 0.01193482 ... 0.01197539 0.00159366 1.        ]]


In [88]:
print(similarity.shape)

(50000, 50000)


In [1]:
movie_name = input(' Enter your favourite movie name : ')

KeyboardInterrupt: Interrupted by user

In [98]:
list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Grandpa Comes Back from Germany', 'Kids Playground', 'The Forgotten Chapter', 'Day of Rain', 'Hop Picking In Kent', 'The Law and the Outlaw', 'Mucho Locos', 'The Joy of the Guitar Riff', 'Extreme', 'The Illegal', 'Dark Moon', 'Kip Curry', 'Battle of New Orleans', 'Wer einsam ist, der hat es gut weil keiner da, der Ihm was tut', 'Lily of the Dust', 'Ta simadia tis vias', 'Husband Factor', 'The Stone Guest', 'Heredarán la tierra', 'Winsor Pilates: The Back Workout', 'Skattjakten', 'Der Unbestechliche', 'The Two of Us', 'Sri Chidambaram Garu', 'The Curse of Taishin', 'The Forgotten Era', 'The Courrier', 'Herbie Goes to Monte Carlo', 'Death on the Run', 'Bamboo Stories', 'Repati Velugu', 'Paramasivan', 'Karalahti', 'Unter Wasser atmen - Das zweite Leben des Dr. Nils Jent', 'Bleau', 'Baked in Brooklyn', 'The Fateful Diamonds', "The Crime Doctor's Gamble", 'Škola hrou', 'The Black Cat', 'Resistance', 'شوقي بيه عريس', 'Strange Love', 'Cinéma antillais, un cinéma en résistance', 'Burning Hot

In [99]:
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['Kids Playground', 'Playground', "The Devil's Playground"]


In [100]:
close_match = find_close_match[0]
print(close_match)

Kids Playground


In [101]:
index_of_the_movie = movies_data[movies_data['title'] == close_match].index[0]

print(index_of_the_movie)

1


In [105]:
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score[:10])

[(0, np.float64(0.01067986960834592)), (1, np.float64(1.0000000000000002)), (2, np.float64(0.014633317366307116)), (3, np.float64(0.03202641629379065)), (4, np.float64(0.009502010990075008)), (5, np.float64(0.03834753047092163)), (6, np.float64(0.009453143016051501)), (7, np.float64(0.022046170066512452)), (8, np.float64(0.027805580183427575)), (9, np.float64(0.02072181041018904))]


In [103]:
len(similarity_score)

50000

In [106]:
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies[:10])

[(1, np.float64(1.0000000000000002)), (12879, np.float64(0.14784242001045728)), (47071, np.float64(0.14066567385414996)), (24194, np.float64(0.13395048668105763)), (7583, np.float64(0.12640328246716787)), (33077, np.float64(0.12489221944145609)), (41463, np.float64(0.12274093604460674)), (21259, np.float64(0.12248184036703412)), (20775, np.float64(0.12197266402852891)), (47628, np.float64(0.11693006712884374))]


In [107]:
print('Movies suggested for you:\n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data.iloc[index]['title']
  if i < 30:
    print(i, '.', title_from_index)
  i += 1

Movies suggested for you:

1 . Kids Playground
2 . Devil Girls
3 . Islands. Alexander Sokurov
4 . Spring Selection
5 . How Long Does Man Live?
6 . Alex's Story
7 . A Conversation Between Parents
8 . The Brothers Karamazov
9 . For Better or Worse
10 . HOME SCHOOL
11 . Two and One
12 . K Sobytijam v Ispanii
13 . Koschey
14 . Love and Death in the Afternoon
15 . Short breath
16 . Quarantime
17 . Offline
18 . Worth Waiting For
19 . Peter's Odyssey
20 . Time of Joy
21 . Peer Gynt
22 . By the Call of the Heart
23 . Fall Out
24 . 15 Days
25 . Photo
26 . The dad
27 . Artyom
28 . Maturant
29 . To the People's Power


Movie Recommendation Sytem

In [110]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data['title'] == close_match].index[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . Fall Out
2 . Belmondo: The Incorrigible
3 . The Smuggler
4 . Baptême
5 . The Apprentice
6 . Le Petit Matin
7 . Outward Signs of Wealth
8 . Zone Red
9 . L'Emprise
10 . Jean-François-Xavier de...
11 . Feu sur le candidat
12 . فيها الملح والسكر أو مبغاتش تموت
13 . The Boss
14 . Letter From A Hitman
15 . Adrien's Story
16 . To Russia On Foot or How to Finish the Film
17 . Le Socrate
18 . Kodrat
19 . The Grip
20 . Are You Engaged to a Greek Sailor or an Airline Pilot?
21 . Game Over
22 . Lien de parenté
23 . The Children of Tehran
24 . Les trois chapeaux claques
25 . Un an
26 . Ariane: A Space Epic
27 . Itinéraire bis
28 . L.627
29 . Rapax
